### ISSUE TITLE
Evaluate removing Spring Security

### ISSUE THREAD

**Issue by tulioag** [vaadin/bakery-app-starter-flow-spring#738]
Currently using Spring Security doesn't seem to be providing great value. There is much boilerplate needed for making it work and removing it will probably make the code base smaller. Dynamic routes can be added after login depending on the user's role as an alternative security solution.

The current boilerplate could be moved to a separate addon. In that case it could make sense to use it still.

Relates to #736

**Comment by web-padawan** [comment]
Covered by https://github.com/vaadin/bakery-app-starter-flow-spring/commit/9a19c9a7f1cb3d2f1e139acd4e9f51342e893b3e.
