### ISSUE TITLE
Use @CssImport instead of shared-styles.js

### ISSUE THREAD

**Issue by Legioth** [vaadin/bakery-app-starter-flow-spring#940]
Using `shared-styles.js` to write CSS inside HTML inside JS is not best practice starting from Vaadin 14. Instead, those styles could be split up into separate CSS files that are loaded using appropriate `@CssImport` annotations.

See https://github.com/vaadin/beverage-starter-flow/pull/403 for an example of a similar conversion.

**Comment by web-padawan** [comment]
Fixed by adding custom theme in https://github.com/vaadin/bakery-app-starter-flow-spring/commit/d20e81ec13070970278158342cea372ec928b5b2.
